cc_test(
    name = "dashboard_json_test",
    size = "small",
    srcs = ["dashboard_json.cpp"],
    deps = [
        "@gtest//:gtest_main",
        "//dashboard/src:dashboard_json",
        "//openconsult/src:openconsult",
    ],
)
